// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnZY8gW8QzCyj8HiGn1eysJZTfxVPODrQ',
    appId: '1:559715859738:web:81e0dfca7712c53b4bc0a3',
    messagingSenderId: '559715859738',
    projectId: 'healthify-app-c12d7',
    authDomain: 'healthify-app-c12d7.firebaseapp.com',
    storageBucket: 'healthify-app-c12d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1Fju9iG9wDEIV2EdCLmV7RY-umGFj_0',
    appId: '1:559715859738:android:964f1345ba3825eb4bc0a3',
    messagingSenderId: '559715859738',
    projectId: 'healthify-app-c12d7',
    storageBucket: 'healthify-app-c12d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6vnPQZnJ5CyL-OBhBIHbyo2Vikw_CZM',
    appId: '1:559715859738:ios:829b2f4468b603744bc0a3',
    messagingSenderId: '559715859738',
    projectId: 'healthify-app-c12d7',
    storageBucket: 'healthify-app-c12d7.firebasestorage.app',
    iosBundleId: 'com.example.medhealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc6vnPQZnJ5CyL-OBhBIHbyo2Vikw_CZM',
    appId: '1:559715859738:ios:829b2f4468b603744bc0a3',
    messagingSenderId: '559715859738',
    projectId: 'healthify-app-c12d7',
    storageBucket: 'healthify-app-c12d7.firebasestorage.app',
    iosBundleId: 'com.example.medhealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnZY8gW8QzCyj8HiGn1eysJZTfxVPODrQ',
    appId: '1:559715859738:web:b88a6d7b3db69a674bc0a3',
    messagingSenderId: '559715859738',
    projectId: 'healthify-app-c12d7',
    authDomain: 'healthify-app-c12d7.firebaseapp.com',
    storageBucket: 'healthify-app-c12d7.firebasestorage.app',
  );

}